# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: install pandoc
      run: sudo apt install -y pandoc
    - name: run pandoc
      run: pandoc *.markdown -f markdown -t html -s -o result.html
    - name: Static files storage
  # You may pin to the exact commit or the version.
  # uses: sylvanld/action-storage@ae3e57af3494b0970af77a20816b976d856ced2d
      uses: sylvanld/action-storage@v1
      with:
        # Name of the branch that will be used for storage
        storage-branch: gh-storage
         # Path to the file that will be saved
        src: result.html
    # Path in storage branch where the file will be saved
        dst: result.html
    # Commit message associated with this modification in storage branch
